# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

on: [push, pull_request]

jobs:
  e2e:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - run: npm ci
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      working-directory: playground
      
    - run: npm run build:main
      working-directory: playground
    - run: npm run build:preload
      working-directory: playground
    - run: npm run build:renderer
      working-directory: playground
    - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm test
      working-directory: playground
